name: Dev environment install scripts

on: [pull_request]

jobs:
  test-dev-windows:
    runs-on: [self-hosted, windows]
    steps:
      - name: Test dev environment on Windows
        uses: actions/checkout@v2
        run: ./windows10_configure_dev_env.ps1
  test-dev-ubuntu:
    runs-on: [self-hosted, linux]
    steps:
      - name: Test dev environment on Ubuntu
        uses: actions/checkout@v2
        run: ./ubuntu18.04_configure_dev_env.sh
  test-dev-macos:
    runs-on: [self-hosted, macos]
    steps:
      - name: Test dev environment on macOS
        uses: actions/checkout@v2
        run: ./macos10.15_configure_dev_env.sh
