name: Test install scripts

on: [push]

jobs:
  test-dev-windows:
    runs-on: [self-hosted, windows]
    steps:
      - name: Test dev environment on Windows
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/RomainFallet/symfony-dev-deploy/master/windows10_configure_dev_env.ps1'))
