name: Dev environment install scripts

on: [pull_request]

jobs:
  test-dev-windows:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v2
      - name: Test dev environment on Windows
        run: ./windows10_configure_dev_env.ps1
  test-dev-ubuntu:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: Test dev environment on Ubuntu
        run: ./ubuntu18.04_configure_dev_env.sh
  test-dev-macos:
    runs-on: [self-hosted, macos]
    steps:
      - uses: actions/checkout@v2
      - name: Test dev environment on macOS
        run: echo ${GITHUB_REF#refs/heads/} && ./macos10.15_configure_dev_env.sh
