name: Test install scripts

on: [push]

jobs:
  windows:
    runs-on: [self-hosted, windows]
    steps:
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/RomainFallet/symfony-dev-deploy/master/windows10_configure_dev_env.ps1'))
